import { CapstoneProject, Task, MilestonePhase, StandupEntry, RevisionItem } from '../types';

const GEMINI_LOCAL_KEY = 'capstoneflow_gemini_api_key';

export const getGeminiApiKey = (): string => {
  const envKey = import.meta.env.VITE_GEMINI_API_KEY;
  if (typeof envKey === 'string' && envKey.trim() !== '' && !envKey.includes('placeholder')) {
    return envKey.trim();
  }
  const stored = localStorage.getItem(GEMINI_LOCAL_KEY);
  return stored ? stored.trim() : '';
};

export const setGeminiApiKey = (key: string) => {
  if (key.trim()) {
    localStorage.setItem(GEMINI_LOCAL_KEY, key.trim());
  } else {
    localStorage.removeItem(GEMINI_LOCAL_KEY);
  }
};

export const isGeminiConfigured = (): boolean => {
  const key = getGeminiApiKey();
  return key.length > 10;
};

// Generic REST call to Gemini 1.5 / 2.0 Flash
async function callGeminiApi(prompt: string, systemInstruction?: string): Promise<string> {
  const apiKey = getGeminiApiKey();
  if (!apiKey) {
    throw new Error('Gemini API key is not configured. Add VITE_GEMINI_API_KEY or set it in Settings.');
  }

  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;

  const body: any = {
    contents: [
      {
        role: 'user',
        parts: [{ text: prompt }]
      }
    ],
    generationConfig: {
      temperature: 0.4,
      topK: 40,
      topP: 0.95,
      maxOutputTokens: 2048
    }
  };

  if (systemInstruction) {
    body.systemInstruction = {
      parts: [{ text: systemInstruction }]
    };
  }

  const response = await fetch(endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(body)
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.error?.message || `Gemini API error (Status ${response.status})`);
  }

  const data = await response.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) {
    throw new Error('No response text generated by Gemini.');
  }

  return text;
}

// 1. AI Task / Ticket Breakdown
export interface GeneratedTaskBreakdown {
  title: string;
  description: string;
  problemStatement: string;
  subtasks: string[];
  whatToFix: string[];
  acceptanceCriteria: string[];
  storyPoints: number;
  estimatedHours: number;
  folder: string;
}

export const generateTaskBreakdown = async (
  featureIdea: string,
  category = 'code'
): Promise<GeneratedTaskBreakdown> => {
  const systemInstruction = `You are a Senior Software Architect and Capstone Project Lead. Given a task or feature request for a student capstone project, decompose it into a structured technical ticket with atomic subtasks, acceptance criteria, and realistic effort estimates. Always return valid JSON only, without markdown backticks.`;

  const prompt = `Decompose this capstone task: "${featureIdea}" in category "${category}".
Return a JSON object with this exact structure:
{
  "title": "Clear concise action title (e.g. Implement JWT Auth Flow)",
  "description": "2-3 sentences explaining technical scope and objectives",
  "problemStatement": "Why this task is needed and what problem it solves",
  "subtasks": ["Subtask 1", "Subtask 2", "Subtask 3", "Subtask 4"],
  "whatToFix": ["Key implementation step 1", "Key implementation step 2", "Key implementation step 3"],
  "acceptanceCriteria": [
    "AC 1: Must handle ...",
    "AC 2: Unit tests must pass for ...",
    "AC 3: Response latency must be under ..."
  ],
  "storyPoints": 5,
  "estimatedHours": 10,
  "folder": "src/features/${category}"
}`;

  try {
    if (isGeminiConfigured()) {
      const raw = await callGeminiApi(prompt, systemInstruction);
      const cleanJson = raw.replace(/```json/g, '').replace(/```/g, '').trim();
      const parsed = JSON.parse(cleanJson);
      return {
        title: parsed.title || featureIdea,
        description: parsed.description || '',
        problemStatement: parsed.problemStatement || '',
        subtasks: Array.isArray(parsed.subtasks) ? parsed.subtasks : [],
        whatToFix: Array.isArray(parsed.whatToFix) ? parsed.whatToFix : [],
        acceptanceCriteria: Array.isArray(parsed.acceptanceCriteria) ? parsed.acceptanceCriteria : [],
        storyPoints: typeof parsed.storyPoints === 'number' ? parsed.storyPoints : 5,
        estimatedHours: typeof parsed.estimatedHours === 'number' ? parsed.estimatedHours : 8,
        folder: parsed.folder || `src/${category}`
      };
    }
  } catch (err) {
    console.warn('Gemini API call failed, using intelligent offline generator fallback:', err);
  }

  // Intelligent Offline Rule-Based Fallback
  const lower = featureIdea.toLowerCase();
  const subtasksList = [
    `Design data schema and type contracts for ${featureIdea}`,
    `Implement core business logic and error boundaries`,
    `Write unit and integration verification tests`,
    `Connect frontend state and verify end-to-end user flow`
  ];

  if (lower.includes('auth') || lower.includes('login')) {
    subtasksList[0] = 'Define token payload and session storage interface';
    subtasksList[1] = 'Implement PKCE OAuth flow and route guards';
  } else if (lower.includes('database') || lower.includes('sql') || lower.includes('supabase')) {
    subtasksList[0] = 'Draft PostgreSQL schema migrations and foreign keys';
    subtasksList[1] = 'Implement indexing and Row Level Security (RLS) policies';
  }

  return {
    title: featureIdea,
    description: `Implement ${featureIdea} according to capstone system requirements and architecture specifications.`,
    problemStatement: `Required to fulfill core capstone objectives for milestone progress and system integration.`,
    subtasks: subtasksList,
    whatToFix: [
      `Implement core module logic`,
      `Add input validation and boundary checks`,
      `Document API interface for team review`
    ],
    acceptanceCriteria: [
      `Functional implementation complete with 0 runtime errors`,
      `All edge cases and null checks verified`,
      `Code formatted according to team conventions and reviewed`
    ],
    storyPoints: 5,
    estimatedHours: 8,
    folder: `src/modules/${category}`
  };
};

// 2. AI Executive Adviser Report Generator
export const generateAdviserReportAI = async (
  project: CapstoneProject,
  tasks: Task[],
  phases: MilestonePhase[],
  standups: StandupEntry[],
  revisions: RevisionItem[]
): Promise<string> => {
  const completedTasks = tasks.filter(t => t.status === 'done');
  const inProgressTasks = tasks.filter(t => t.status === 'in_progress' || t.status === 'peer_review' || t.status === 'adviser_review');
  const activePhase = phases.find(p => p.id === project.currentPhaseId) || phases[0];

  const systemInstruction = `You are a professional Academic Project Coordinator generating an Executive Capstone Progress Briefing for Faculty Adviser ${project?.adviser?.name || 'Faculty Adviser'}. Provide a well-structured, formal, objective Markdown report suitable for university department evaluation.`;

  const contextData = `
Project Title: ${project.title}
Team Name: ${project.teamName || `${project.title} Team`}
Faculty Adviser: ${project?.adviser?.name || 'Faculty Adviser'} (${project?.adviser?.department || project?.organization || 'Academic Supervision'})
Target Defense: ${project.targetDefenseDate}
Current Active Phase: Phase ${activePhase?.id} - ${activePhase?.title} (${activePhase?.progressPercentage}% Complete)
Overall Progress: ${project.overallProgress}%

Completed Tasks (${completedTasks.length}):
${completedTasks.map(t => `- [DONE] ${t.title} (${t.storyPoints} pts, ${t.loggedHours} hrs)`).slice(0, 10).join('\n')}

In-Progress Tasks (${inProgressTasks.length}):
${inProgressTasks.map(t => `- [IN PROGRESS] ${t.title} (Due: ${t.dueDate})`).slice(0, 8).join('\n')}

Recent Standups (${standups.length}):
${standups.slice(0, 5).map(s => `- ${s.date}: Plan: ${s.todayPlan} | Blockers: ${s.blockers}`).join('\n')}

Adviser Revision Matrix:
- Total Items: ${revisions.length}
- Resolved: ${revisions.filter(r => r.status === 'resolved' || r.status === 'verified').length}
- Pending Action: ${revisions.filter(r => r.status === 'pending' || r.status === 'in_progress').length}
`;

  const prompt = `Generate a comprehensive Executive Capstone Progress Report based on the following data:
${contextData}

Include:
1. Executive Summary & Readiness Verdict
2. Milestone Phase Status & Gate Deliverables
3. Engineering Sprints & Velocity Highlights
4. Panel Revision Matrix Resolution Status
5. Upcoming Critical Path & Action Items for the Adviser Meeting.`;

  try {
    if (isGeminiConfigured()) {
      return await callGeminiApi(prompt, systemInstruction);
    }
  } catch (err) {
    console.warn('Gemini API call failed, generating template report:', err);
  }

  // High-Quality Fallback Template Report
  return `# Executive Capstone Progress Briefing
**Project:** ${project.title}  
**Team:** ${project.teamName}  
**Faculty Adviser:** ${project?.adviser?.name || 'Faculty Adviser'} (${project?.adviser?.department || project?.organization || 'Academic Supervision'})  
**Date Generated:** ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}  
**Target Defense:** ${project.targetDefenseDate}  
**Overall Readiness:** ${project.overallProgress}%  

---

### 1. Executive Summary
The capstone development team is currently progressing through **Phase ${activePhase?.id}: ${activePhase?.title}**, with an overall milestone completion rate of **${activePhase?.progressPercentage}%**. The technical infrastructure, sprint velocity, and code deliverable pipeline remain on schedule for the targeted defense date of **${project.targetDefenseDate}**.

---

### 2. Engineering Sprints & Velocity Highlights
- **Completed Story Points:** ${completedTasks.reduce((sum, t) => sum + (t.storyPoints || 0), 0)} pts across ${completedTasks.length} verified tickets.
- **Active In-Flight Work:** ${inProgressTasks.length} tasks undergoing active development, peer review, or testing.
- **Key Accomplishments:**
${completedTasks.slice(0, 5).map(t => `  - **${t.title}** (${t.category.toUpperCase()}) — ${t.storyPoints} Story Points`).join('\n')}

---

### 3. Milestone Deliverables Checklist
${phases.map(p => `
#### Phase ${p.id}: ${p.title} (${p.progressPercentage}%) — *${p.status.toUpperCase()}*
${p.keyDeliverables.map(d => `- [${d.completed ? 'x' : ' '}] ${d.title} ${d.requiredForDefense ? '*(Defense Gate)*' : ''}`).join('\n')}
`).join('\n')}

---

### 4. Adviser Feedback & Revision Resolution
- **Total Panel Revision Items:** ${revisions.length}
- **Successfully Resolved / Verified:** ${revisions.filter(r => r.status === 'resolved' || r.status === 'verified').length}
- **Pending Implementation:** ${revisions.filter(r => r.status === 'pending' || r.status === 'in_progress').length}

---

### 5. Next Action Items for Faculty Consultation
1. Review Phase ${activePhase?.id} key deliverables and sign-off readiness.
2. Verify resolved items in the Panel Revision Matrix.
3. Align on sprint roadmap for upcoming milestone gate.
`;
};

// 3. AI Daily Standup Polisher
export const polishStandupWithAI = async (
  yesterday: string,
  today: string,
  blockers: string
): Promise<{ yesterday: string; today: string; blockers: string }> => {
  const prompt = `Clean up and polish these student daily standup notes into clear, professional, concise engineering bullet points.
Yesterday: "${yesterday}"
Today: "${today}"
Blockers: "${blockers}"

Return a JSON object only:
{
  "yesterday": "Polished bullet points of what was completed",
  "today": "Polished bullet points of planned work",
  "blockers": "Clear concise statement of blockers (or 'No active blockers.')"
}`;

  try {
    if (isGeminiConfigured()) {
      const raw = await callGeminiApi(prompt, 'You are an Agile Scrum Master assistant. Format notes into clear, bulleted standup updates. Return valid JSON only.');
      const cleanJson = raw.replace(/```json/g, '').replace(/```/g, '').trim();
      const parsed = JSON.parse(cleanJson);
      return {
        yesterday: parsed.yesterday || yesterday,
        today: parsed.today || today,
        blockers: parsed.blockers || blockers || 'No active blockers.'
      };
    }
  } catch (err) {
    console.warn('Gemini Standup polish failed, using formatting fallback:', err);
  }

  return {
    yesterday: yesterday.trim(),
    today: today.trim(),
    blockers: blockers.trim() || 'No active blockers.'
  };
};
